[book]
authors = ["lowRISC"]
language = "en"
multilingual = false
src = "."
title = "Software Documentation"

[preprocessor.variables]
use_env = true

[preprocessor.variables.variables]
before = [ "links" ]

[output.html]
fold = { enable = true, level = 1 }
site-url = "/software/"
