[book]
authors = ["lowRISC"]
language = "en"
multilingual = false
src = "."
title = "Software Documentation"

# cargo install mdbook-variables
[preprocessor.variables.variables]
url_root = "0.0.0.0:8000/doc"

[output.html]
fold = { enable = true, level = 1 }
site-url = "/software/"
