[book]
authors = ["lowRISC"]
language = "en"
multilingual = false
src = "src"
title = "Use-Cases Book"

[preprocessor.variables]
use_env = true

[preprocessor.variables.variables]
before = [ "links" ]

[output.html]
site-url = "/use-cases/"
