[book]
authors = ["lowRISC"]
language = "en"
multilingual = false
src = "."
title = "OpenTitan Hardware Documentation"

[preprocessor.variables]
use_env = true

[preprocessor.variables.variables]
before = [ "links" ]

[output.html]
fold = { enable = true, level = 1 }
site-url = "/hardware/"

[preprocessor.reggen]
command = "../util/mdbook-reggen.py"
