[book]
authors = ["lowRISC"]
language = "en"
multilingual = false
src = "."
title = "OpenTitan Documentation"

[output.html]
theme = "../doc/theme"
default-theme = "opentitan-light"
fold = { enable = true, level = 1 }
