[book]
authors = ["lowRISC"]
language = "en"
multilingual = false
src = "."
title = "OpenTitan Hardware Documentation"

[output.html]
fold = { enable = true, level = 1 }
site-url = "/books/hardware/"
